repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        files: \.nix$

      - id: stylua
        name: stylua
        entry: stylua
        language: system
        files: \.lua$
