hash -d cac=$HOME/.cache
hash -d cf=$HOME/.config
hash -d D=$HOME/Downloads
hash -d d=$HOME/Documents
hash -d dt=$HOME/.local/share
hash -d m=$HOME/Media
hash -d sc=$HOME/.local/bin

# source "$HOME/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
# #source "$HOME/.config/zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh"
# source "$HOME/.config/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
# source "$HOME/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
# source "$HOME/.config/zsh/plugins/zsh-nix-shell/nix-shell.plugin.zsh"
# source "$HOME/.config/zsh/plugins/fzf-tab/fzf-tab.zsh"
# source "$HOME/.config/zsh/plugins/better-prompt/better-prompt.zsh"

export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=false
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview 'git diff $word | delta'
zstyle ':fzf-tab:complete:git-log:*' fzf-preview 'git log --color=always $word'
zstyle ':fzf-tab:complete:git-help:*' fzf-preview 'git help $word | bat -plman --color=always'
zstyle ':fzf-tab:complete:git-show:*' fzf-preview \
'case "$group" in
"commit tag") git show --color=always $word ;;
*) git show --color=always $word | delta ;;
esac'
zstyle ':fzf-tab:complete:git-checkout:*' fzf-preview \
'case "$group" in
"modified file") git diff $word | delta ;;
"recent commit object name") git show --color=always $word | delta ;;
*) git log --color=always $word ;;
esac'
zstyle ':fzf-tab:complete:_zlua:*' query-string input
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ''${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':fzf-tab:*' fzf-command fzf
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'
zstyle ':fzf-tab:*' accept-line enter
zstyle ':fzf-tab:*' continuous-trigger '/'

export WORDCHARS="-_"
bindkey -M vicmd '^g' fzf-cd-widget
bindkey -M viins '^g' fzf-cd-widget
bindkey -M vicmd '^f' fzf-file-widget
bindkey -M viins '^f' fzf-file-widget
bindkey -M viins '^w' backward-kill-word
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey -M vicmd '^e' edit-command-line
bindkey -M viins '^e' edit-command-line

function lf() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

if command -v micromamba &> /dev/null ; then
  eval "$(micromamba shell hook --shell zsh)"
fi

if [[ -n ${TMUX:-} && -n ${TMUX_PANE:-} ]] && command -v tmux >/dev/null 2>&1; then
  __tmux_cmdlog_dir="${XDG_STATE_HOME:-$HOME/.local/state}/tmux-command-log/${TMUX_PANE#%}"
  __tmux_cmdlog_file="$__tmux_cmdlog_dir/output.log"
  mkdir -p "$__tmux_cmdlog_dir"
  : >> "$__tmux_cmdlog_file"

  tmux set-option -p -q @command-log-dir "$__tmux_cmdlog_dir" 2>/dev/null || true
  tmux pipe-pane -o -t "$TMUX_PANE" "cat >> ${(q)__tmux_cmdlog_file}" 2>/dev/null || true

  autoload -Uz add-zsh-hook

  __tmux_cmdlog_preexec() {
    local cmd="$1"
    local start

    if [[ "$(wc -c < "$__tmux_cmdlog_file" | tr -d ' ')" -gt 20000000 ]]; then
      : > "$__tmux_cmdlog_file"
    fi

    start="$(wc -c < "$__tmux_cmdlog_file" | tr -d ' ')"
    print -r -- "$cmd" > "$__tmux_cmdlog_dir/cmd"
    print -r -- "$PWD" > "$__tmux_cmdlog_dir/cwd"
    print -r -- "$start" > "$__tmux_cmdlog_dir/start"
    rm -f "$__tmux_cmdlog_dir/end" "$__tmux_cmdlog_dir/status"
  }

  __tmux_cmdlog_precmd() {
    local exit_status="$?"
    local end

    [[ -f "$__tmux_cmdlog_dir/start" ]] || return 0
    end="$(wc -c < "$__tmux_cmdlog_file" | tr -d ' ')"
    print -r -- "$end" > "$__tmux_cmdlog_dir/end"
    print -r -- "$exit_status" > "$__tmux_cmdlog_dir/status"
  }

  add-zsh-hook preexec __tmux_cmdlog_preexec
  add-zsh-hook precmd __tmux_cmdlog_precmd
fi

unsetopt SHARE_HISTORY        # avoid merging/import side effects that can make history feel unstable
setopt APPEND_HISTORY         # append to the history file instead of rewriting it on shell exit
setopt INC_APPEND_HISTORY     # write each command as it is entered
setopt HIST_FCNTL_LOCK        # use file locking so concurrent shells don't clobber history
setopt HIST_SAVE_NO_DUPS      # don't write duplicate entries to the history file
setopt HIST_FIND_NO_DUPS      # skip duplicates when searching history
setopt HIST_REDUCE_BLANKS     # trim superfluous blanks before saving
# TODO: workaround
if [ "$TERM" = "xterm-ghostty" ]; then
  export TERM="xterm-256color"
fi
